python/shark_turbine/dynamo/tensor.py

Allows retrieving the element size of a Tensor based on its datatype, this passes the initial test suite.

Pass initial test suite

---

python/shark_turbine/dynamo/importer.py
python/test/dynamo/importer_basic_test.py

Resolves an issue with the `FxImporter` where arguments that are `!torch.list` types are not properly imported due to the Fx tracer denoting them via `immutable_list` types rather than encapsulating them in an `fx.Node`. Also addresses a case where a python scalar is not parsed into an `fx.Node` but rather retains its python type. For instance, in [`aten.convolution`](https://github.com/llvm/torch-mlir/blob/0109bf705b0dae3b4d55c7a9b180516787cbeac6/include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td#L4583C18-L4583C18) where the "transposed" parameter is passed as false by default - this argument is left as a `bool` and therefore needs to be handled when importing arguments.

Parse list and scalar args for torch ops

---

sync_deps.py

iree: a1caa91f7 2023-08-02 01:48:12 +0000 : Move test_a100 to postsubmit-only (#14546)
torch-mlir: 4c24472d 2023-07-31 07:54:05 -0700 : update PyTorch version to 2.1.0.dev20230731 (#2359)

Bump deps.

---

python/shark_turbine/dynamo/importer.py
python/test/dynamo/importer_basic_test.py

This PR implements proper parsing of `torch.dtype` subclasses to the appropriate `Torch_IntValue` using torch-mlir convention, taken from [here](https://github.com/llvm/torch-mlir/blob/4c24472dea1c9102b898768b0b11e31487e50207/python/torch_mlir/_dynamo_fx_importer.py#L189). We do not support quantized datatypes due to dynamo's lack of support for quantized datatypes outside of a set of specific backends, but may address these cases in the future.

Fix importing torch dtypes

---

python/shark_turbine/dynamo/importer.py
python/shark_turbine/dynamo/tensor.py
python/test/dynamo/importer_basic_test.py
python/test/dynamo/multiple_aten_results_test.py
python/test/dynamo/tensor_test.py

This PR addresses importing torch enum types (`torch.dtype`, `torch.layout`, `torch.memory_format`) by converting them to the proper integer values.

Import torch enum args

---

python/shark_turbine/dynamo/importer.py
python/test/dynamo/importer_basic_test.py

Adds support for a case when importing a list argument whose operands are fx.Nodes rather than scalar constants. We already handle a case like the following `torch.randn((3,3,10))`, here the first argument is a list, `size`, where each element is a scalar constant - however when the list elements are instead the result of other operations then they will be parsed by Dynamo as `fx.Node` types. For instance when we do something like
```
x, y = torch.randn(10), torch.randn(10)
z = torch.cat((x,y), 0)
```
each tensor is actually an `fx.Node` referencing an MlirValue, so we have to extract the corresponding MlirValue to construct the appropriate list value as an argument to the torch operation `cat`.

Support for fx.Node operands in list arguments

---

python/shark_turbine/dynamo/importer.py

This refactors the list construction logic into a new importer method `_import_list_argument`, cases where users explicitly pass lists were handled before in `_import_argument` but when the list arguments are instead filled by default value we have to use essentially the same logic to construct the list. 
For example:
```py
def foo():
m = nn.MaxPool2d(2, 2, 1) # params like 'dilation' are defaulted to a constant list: [1,1]
return m(torch.randn(1,256,256))
```
I implemented this as a class method because the logic for most other cases requires access to the importer's state, and creating a separate method to call from `LITERAL_CONVERTER_MAP` to handle the case with lists made purely of constant values would repeat code (and require breaking the signature convention we are using for this …

Accept default list arguments

---

python/shark_turbine/dynamo/importer.py
python/test/dynamo/importer_basic_test.py
python/test/dynamo/multiple_aten_results_test.py

Marked expected failure for the following test cases: 
1. `aten.chunk` 
- FX node does not have meta_data["tensor_meta"], and fails to emit `result_types` of list of tensors, required for op creation
- Commented `aten.split.Tensor` `aten.unbind.int`would also fail for similar reason in the test case
- Further investigation on torch-mlir, FX graph, Dynamo needed.
2. `tolist` and standard python `list()` 
- `No stacktrace found for following nodes: _tensor_constant0 = self._tensor_constant0` results in lacking `operands` and failure in attaching to op creation, where `aten.lift_fresh_copy` op is invovled

xfail `chunk`, `tolist`, and `list`

---

python/test/generated/evaluate.py
python/test/generated/main.py
python/test/generated/running_tests.md
python/test/generated/stats.py
python/test/generated/testutils.py

Courtesy of `pytorch-jit-paritybench` this adds the ability to run our Turbine importer on the full generated test suite from there and returns a sorted list of errors (by their prevalence in the test suite) for us to triage. Eventually, we can add other test functions for other aspects of Turbine or different device backends. 
How it works is largely explained in `running_tests.md`

Add a larger test suite

---

python/shark_turbine/dynamo/importer.py
python/test/dynamo/importer_backward_test.py

We implemented the followings for this PR:
- Added `importer_backward_test.py', which currently has a simple custom loss function for backward. 
Needs to add test cases including 1) using `func.grad` for backward test, and 2) MNIST Classifier using LeNet for backward test
- Parsing `!torch.none` to store MlirType of none for `result_types` to create required op
- Added `bool` for list construction. 
Test cases mentioned above will be added in the next PR.

Test simple backward

---

python/shark_turbine/dynamo/backends/cpu.py
python/shark_turbine/dynamo/importer.py
python/shark_turbine/dynamo/passes.py
python/test/dynamo/importer_basic_test.py
python/test/dynamo/multiple_aten_results_test.py
python/test/generated/evaluate.py
python/test/generated/main.py
python/test/generated/stats.py
python/test/generated/testutils.py

Adds default decompositions from SHARK to the Turbine import flow, with a test for importing `aten.chunk` which previously failed.
A few design questions:
1) Here I've included all the default decompositions present in SHARK, do we want to keep it this way or should I by default include a more minimal set?
2) I've hardcoded the above set of default decompositions for our CPU backend, but we spoke about making decompositions configurable - do we want a nice, user-facing way to do this or only want this for development purposes? I'm trying to figure out the best way to include this feature without it seeming awkward
Also, adding default decompositions to the generated tests passes an extra 50 cases when considering the first 700 or so test cases (this equates to setting `--limit 100` when …

Add decompositions to import flow

---

python/shark_turbine/known_issues.md

Updated progress about Ephemeral Tensor objects from `aten.lift_fresh_copy` case.

Known issues v2

---

python/shark_turbine/dynamo/passes.py
python/test/generated/evaluate.py

This addresses a slew of "unimplemented" errors in the test suite for any operations that has an available decomposition. The only exception is `aten.smooth_l1_loss` which, despite having a decomposition available in pytorch, is somehow still triggering the same error - we can investigate this later or implement the op if needed.

Add more decompositions

---

python/shark_turbine/dynamo/importer.py
python/shark_turbine/known_issues.md
python/test/dynamo/importer_basic_test.py

This addresses the most common issue in our [known issues doc](https://github.com/nod-ai/SHARK-Turbine/blob/8fcbac138777812f7b244a3182dacbaafb0d046e/python/shark_turbine/known_issues.md), handling optional arguments by using typing metadata present in the `FunctionSchema` for `OpOverload` nodes. It adds a test case (in addition to existing cases handling list arguments) and also removes that issue from the `known_issues.md` document.
This allows us to eliminate the hacky string manipulation and regex logic from the previous implementation.

Handle lists of optional arguments

---

python/test/dynamo/llama_test.py

Add a test case for passing llama through the`turbine_cpu` backend. This replaces all fairscale layers with corresponding vanilla torch layers for simplicity, but we can add these back later once we have llama working. Also removes the `@torch.inference_mode()` decorator to avoid the issue documented [here](https://github.com/pytorch/pytorch/issues/101151), which is not necessarily relevant to the quality of our pipeline.

Add llama test

---

python/test/generated/main.py
python/test/generated/testutils.py

Adds the ability to run tests sequentially in case python threading poses problems for certain machines.

Add sequential option for generated tests

---

python/test/generated/extract_unimpl_ops.sh
python/test/generated/running_tests.md

Adds a utility script to get a list of unimplemented torch ops from torch-mlir using our test suite.

Extract unimplemented ops from generated test suite

---

python/shark_turbine/dynamo/passes.py
python/test/dynamo/importer_basic_test.py

A quick fix to decompose `aten.full` by adding it to CPU decomposition in Turbine.

Fix aten full decomposition

---

python/shark_turbine/dynamo/importer.py

Previously we had a fix that allowed us to pass `lift_fresh_copy` through the importer. However, this fails to actually lower to `linalg` and then `arith` due to an issue in `torch-mlir` where `lift_fresh_copy` causes a failure in the corresponding lowering passes when using torch dynamo, this is a quick fix that replaces this op with an equivalent one: `aten.clone`. This is valid because this is actually the canonical decomposition of `lift_fresh_copy` in `torch-mlir` anyway.

Replace lift_fresh_copy with aten.clone

---

python/shark_turbine/dynamo/importer.py
python/test/dynamo/importer_basic_test.py

Handles a case where there is no `Scalar` equivalent for a torch op which accepts scalar arguments - instead Pytorch promotes such scalars to a 0-rank tensor, which we now do as well.

Promote scalar arguments to tensors when appropriate

---

python/shark_turbine/aot/builder.py
python/shark_turbine/aot/builtins/__init__.py
python/shark_turbine/aot/builtins/globals.py
python/shark_turbine/aot/builtins/jittable.py
python/shark_turbine/aot/builtins/typedef.py
python/shark_turbine/aot/compiled_module.py
python/shark_turbine/aot/procedural.py
python/shark_turbine/dynamo/importer.py
python/shark_turbine/dynamo/passes.py
python/test/aot/globals_test.py

* Introduces `export_parameters` which eagerly generates IR for accessing module parameters. Currently it is just emitting a global for each with an initial value, but this can be controlled with kwargs for more advanced policies.
* Teaches the AOT module builder how to track captured tensors by reference and repatriate them with the module level globals during import.
* Adds a hook to the FxImporter that lets us take control of how to materialize access to py values (other than the default policy of just freezing them as inline constants).
* Switches the AOT pipeline to use a new `torch-to-iree-pipeline`, which is needed in IREE because with these changes, we have deviated from what Torch-MLIR upstream calls "linalg lowering" and need to make alterations. (Needs a patch to land in IREE …

Implement programming model for AOT parameters and globals.

---

python/shark_turbine/aot/builtins/__init__.py
python/shark_turbine/aot/builtins/iree_ir.py
python/shark_turbine/aot/support/ir_imports.py
python/shark_turbine/aot/support/ir_utils.py
python/shark_turbine/aot/support/procedural.py
python/shark_turbine/aot/support/utils.py
tests/aot/iree_procedural_test.py

* Boilerplate and type support for procedural emission of IREE specific IR constructs.
* Dynamic shape aware `tensor_dim`, `tensor_empty`, `tensor_splat` builders.
* Added `tensor_trace` since it was there and easy.
* Unlike upstream MLIR, this layer respects IREE's ranked/op-carried symbolic shapes and does the frontend accounting to make sure that dynamic dims thread through explicitly.
* I was really aiming at the slice ops but started simple. Will get to those next.
* Eventually, this will grow to support all procedural IR that IREE supports (loops, conditionals, streamable calls, etc). And at a future point, I will sugar it appropriately.

Start building out IREE procedural meta-language.

---

requirements.txt
tests/dynamo/importer_basic_test.py
tests/dynamo/llama_test.py
tests/dynamo/mninst_test.py
torchvision-requirements.txt

Added MNIST training test case.
This requires torch-vision, so added it to the requirement. 
Furthermore, the change in cpu pass to `torch-to-iree`, which needs the change in IREE pass to be landed and reflected in the IREE release, will fail all the tests with `empty_strided` involved. As soon as IREE's new release is available, the xfails can be removed.

Test mnist training

---

python/shark_turbine/dynamo/passes.py

Added to cpu_decomposition`aten._log_softmax`, `aten.nll_loss_forward`, `aten._to_copy`,
Decomposition of `aten.scalar_tensor` op at torch-mlir has also landed. (https://github.com/llvm/torch-mlir/pull/2481).

Added decomposition ops for MNIST test debugging

---

python/shark_turbine/aot/support/ir_utils.py
python/shark_turbine/dynamo/type_conversion.py
tests/aot/jittable_test.py

Also adds a primitive error reporting facility to the verifiers that dumps the IR to the temp directory. This needs something better eventually but at least lets us debug for now.

Fix handling of signed integer tensor dtypes when converting to native.

---

docs/developer/known_issues.md
python/shark_turbine/aot/builtins/jittable.py
python/shark_turbine/dynamo/passes.py
tests/dynamo/mninst_test.py

This PR includes the following:
1. Added linear model in MNIST training test case
2. Added some ops into decomposition passes
3. Documented issues about some inputs to `aten.where` not wrapped to be fake tensors due to upstream PyTorch issue. 
As of now, MNIST forward graph is lowered, but during the training (i.e backward) lowering fails due to upstream PyTorch issue. This will be raised as an issue in Turbine repo.

Add Linear model to MNIST test, and decompose some backward ops

---

.github/workflows/test.yml
examples/aot_mlp/mlp_export_simple.py
python/shark_turbine/aot/__init__.py
python/shark_turbine/aot/exporter.py
python/shark_turbine/dynamo/passes.py
pytorch-cpu-requirements.txt
tests/examples/aot_mlp_test.py
torchvision-requirements.txt

* Adds full compilation support (as opposed to just stopping at the exported IR).
* Adds a sample which exercises the entire flow.

Add a simple `aot.export` entrypoint for one-short nn.Module export.

---

examples/eager_mlp/mlp_eager_simple.py
tests/dynamo/mninst_test.py

Another way to address the issue https://github.com/nod-ai/SHARK-Turbine/issues/93, where not all inputs are tensors depending on batchsize during execution. We simply set `drop_last=True` in the data loader.

Fix mnist test dataloader

---

examples/aot_mlp/mlp_export_simple.py
examples/llama2_inference/stateless_llama.py

Transposed the global state to allow continuous memory access while updating. Previously only the 0th idx of the 2nd dim was getting updated on initialization. Also update needs to be stored back to the global variable. Couple other minor bugfixes.

[llama] transpose global state

---

python/shark_turbine/aot/builtins/globals.py
python/shark_turbine/aot/support/ir_imports.py
python/shark_turbine/aot/support/ir_utils.py
python/shark_turbine/aot/support/procedural/globals.py
python/shark_turbine/aot/support/utils.py
tests/aot/globals_test.py
tests/aot/iree_procedural_test.py
tests/aot/jittable_test.py

* Adds kwargs to builtins that create parameters and globals:
* external=True : Emit as an external parameter
* external_scope : Set an explicit external scope
* name_mapper : Callback to map logical name on the module to parameter name
Requires an IREE nightly bump.

Adds support for IREE external parameters at module export time.

---

python/shark_turbine/transforms/general/rename_parameters.py
tests/transforms/general/rename_parameters_test.py

The implementation of this pass is really gross because there is missing IREE Python bindings for introspecting the #stream.parameter.named attribute. I'll clean that up later once I get upstream in better shape. In the meantime, this should work.

Add a pass to rename parameters.

---

examples/llama2_inference/remap_gguf.py
examples/llama2_inference/stateless_llama.py

- Enables use of external parameters for stateless llama example
- Provides mapping for llama.cpp gguf weights to torch llama weights
- Adds flag --external_weight_file for path containing weights to load when using run_vmfb
- Adds flag --vmfb_path for path to vmfb file when using run_vmfb
- Adds flag --external_weights for generating IR/VMFB with global params expected from external file

Support for external param in stateless llama and some flags

---

python/shark_turbine/transforms/quantization/mm_group_quant.py
python/turbine_models/custom_models/stateless_llama.py

- Modifies mm_group_quant to work with brevitas safetensors, needs work to generalize
- Changes compiler to use torch as input to enable quantization of torch ir

Adds support to use brevitas quantized weights for stateless_llama

---

python/turbine_models/gen_external_params/gen_external_params.py
python/turbine_models/model_builder.py

- Script to generate safetensors from an hf model using model_builder.py
- Provides support for brevitas quantized paramters

Adds script to generate external parameters as safetensors

---

python/shark_turbine/aot/builtins/globals.py
python/shark_turbine/aot/support/ir_utils.py
requirements.txt
tests/aot/globals_test.py

We previously removed this because without compiler support for marking globals as uninitialized, it was a footgun. Adding back now that IREE has support.
Includes a bump to 20231121.715.

Support uninitialized=True properly with new attribute.

---

python/turbine_models/custom_models/stateless_llama.py
python/turbine_models/gen_external_params/gen_external_params.py

- Adds support to compile vmfb to different device backends including cpu/vulkan/rocm/cuda
- Adds flags for device, iree_target_triple (backend device specific info) and vulkan max allocation
- Minor fix to gen_external_params when not doing quantization

Adds gpu support for stateless llama

---

python/shark_turbine/kernel/_support/tracing.py
python/shark_turbine/kernel/_support/typing.py
python/shark_turbine/kernel/gen/thread.py
python/shark_turbine/kernel/lang/types.py
tests/kernel/simple_kernel_test.py
tests/kernel/types_test.py

* Implements dependent typing and symbols for KernelBuffer and Grid.
* Makes `tk.gen.thread` take explicit grid symbols.
* Leaves room for adding/inferring sufficient constraints to enable dynamic vectorization.

[tk] Fill out the type system.

---

python/shark_turbine/kernel/_support/indexing.py
python/shark_turbine/kernel/_support/tracing.py
python/shark_turbine/kernel/compiler/analysis.py
python/shark_turbine/kernel/compiler/base.py
python/shark_turbine/kernel/compiler/builder.py
python/shark_turbine/kernel/compiler/ir.py
python/shark_turbine/kernel/compiler/op_matchers.py
python/shark_turbine/kernel/compiler/vector_codegen.py
python/shark_turbine/kernel/gen/thread.py
tests/kernel/analysis_test.py
tests/kernel/indexing_test.py
tests/kernel/vector_codegen_test.py

* Adds arithmetic binary broadcast.
* Adds f32 arithmetic.
* Handles torch ops exp, max, sum (only reduce to scalar at the moment).
* General python signature validation and unpacking.
* Some initial attribute propagation work needed to handle unsigned properly.
* A start at full generality for symbolic dimensions and slice analysis. Needs to be reworked before too long but this gets us basic functionality on static kernels while leaving room for dynamic to emerge.

[tk5] Implement slice analysis and sufficient op coverage for a softmax kernel.

---

python/shark_turbine/aot/builtins/jittable.py
python/shark_turbine/aot/compiled_module.py
python/shark_turbine/aot/support/ir_utils.py
python/shark_turbine/aot/support/procedural/globals.py
python/shark_turbine/aot/support/procedural/iree_emitter.py
python/shark_turbine/importers/fx_importer.py
python/shark_turbine/importers/utils.py
tests/aot/iree_procedural_test.py
tests/aot/jittable_test.py
tests/dynamo/importer_basic_test.py

(https://github.com/stellaraccident/llama.turbine)
* Dedup captured tensors on fx import.
* Allow import of complex64/128 now that using DenseResourceElementsAttr.
* Add index casting to IREE.splat_tensor.
* Support getting a tensor dimension as a specific type.
* Preserve FxImporter's py_attr_tracker across an entire module build.

Various fixes to enable my experimental llama.turbine port of llamacpp to compile.

---

python/turbine_models/custom_models/stateless_llama.py

Note:
we still need a programmatic solution to getting an appropriate pytree spec for the state schema.

(stateless_llama) Use HF model config for some variables.

---

python/shark_turbine/kernel/_support/indexing.py
python/shark_turbine/kernel/_support/regions.py
python/shark_turbine/kernel/_support/tracing.py
python/shark_turbine/kernel/compiler/analysis.py
python/shark_turbine/kernel/compiler/ir.py
python/shark_turbine/kernel/compiler/vector_codegen.py
python/shark_turbine/kernel/gen/thread.py
python/shark_turbine/kernel/lang/prims.py
python/shark_turbine/kernel/lang/types.py
python/shark_turbine/kernel/ops/__init__.py
python/shark_turbine/kernel/ops/control_flow.py
python/shark_turbine/kernel/ops/core.py
python/shark_turbine/kernel/ops/math.py
python/shark_turbine/kernel/ops/memory.py
python/shark_turbine/kernel/ops/reduction.py
tests/kernel/dispatch_codegen_test.py
tests/kernel/simple_kernel_test.py
tests/kernel/vector_codegen_test.py

This PR supports tracing a function within a separate tracer as a "subgraph". This allows us to trace loop bodies instead of unrolling them.
Along with subgraph tracing, this patch adds several features to enable tracing a gemm kernel:
- Instead of doing slicing, add explicit tkl.load/tkl.store ops. Personally, I feel slicing may not be the way to go forward as we always have a constant sized output from the slice. If we go with slicing, we have to analyze if it's constant sized which is not worth it.
- Add support for tkl.constant, tkl.dot, tkl.for_loop.
- Add a new "Vector" class, which is a tensor like class supporting computations over it. I'm not a fan of using pytorch ops directly since I don't get control over the op signature.
I did not add support for eager executing these …

[TK] Subgraph Tracing to support control flow

---

python/shark_turbine/kernel/_support/tracing.py
python/shark_turbine/kernel/compiler/builder.py
python/shark_turbine/kernel/compiler/vector_codegen.py
python/shark_turbine/kernel/lang/prims.py
python/shark_turbine/kernel/ops/__init__.py
python/shark_turbine/kernel/ops/math.py
python/shark_turbine/kernel/ops/reduction.py
python/shark_turbine/kernel/ops/shape_manipulation.py
tests/kernel/dispatch_codegen_test.py
tests/kernel/simple_kernel_test.py
tests/kernel/vector_codegen_test.py

Add new ops:
- tkl.exp2 (math)
- tkl.max (reduce max)
- tkl.sum (reduce sum)
- tkl.broadcast (broadcast leading dims)
- tkl.broadcast_in_dim (broadcast specific dimensions)
- tkl.transpose (transpose)

[TK] Add support for ops required for Flash Attention 2

---

python/shark_turbine/aot/exporter.py

The function signatures seem to have changed after 
https://github.com/llvm/llvm-project/pull/75099
without this change I get
```
TypeError: print(): incompatible function arguments. The following argument types are supported:
1. (self: iree.compiler._mlir_libs._mlir.ir._OperationBase, state: mlir::python::PyAsmState, file: object = None, binary: bool = False) -> None       
2. (self: iree.compiler._mlir_libs._mlir.ir._OperationBase, large_elements_limit: Optional[int] = None, enable_debug_info: bool = False, pretty_debug_info: bool = False, print_generic_op_form: bool = False, use_local_scope: bool = False, assume_verified: bool = False, file: object = None, binary: bool = False) -> None
```
I think the file vraible is being confused with the AsmState variable.

Fix mlir printer arguments to match new signatures

---

core/shark_turbine/importers/fx_importer.py
core/tests/dynamo/importer_basic_test.py

Adds an escape hatch from creating a DenseResourceElementsAttr for single value tensors into DenseElementsAttr.
Addresses #398

[fx_importer] Add support for 0D tensors

---

models/turbine_models/custom_models/stateless_llama.py
models/turbine_models/gen_external_params/gen_external_params.py

Models with GQA implemented would not have the same number of heads for K,V vs Query. Hence we need to query `num_key_value_heads` attribute to see if we require different value for KV cache size.
Not all model has `num_key_value_heads` as a part of their config such as QWEN. Phi has it, but it is set to null, hence the code is structured this way to handle those cases.

[stateless-llm]Query num_key_value_heads when available to support GQA models.

---

core/shark_turbine/dynamo/passes.py
models/turbine_models/custom_models/sd_inference/schedulers.py
models/turbine_models/custom_models/sd_inference/schedulers_runner.py
models/turbine_models/custom_models/sd_inference/utils.py
models/turbine_models/custom_models/sd_inference/vae_runner.py
models/turbine_models/tests/sd_test.py

TODO: Need to review/merge [diffusers](https://github.com/huggingface/diffusers/pull/6878) and [torch-mlir](https://github.com/llvm/torch-mlir/pull/2875) PR's and update them to use the changes.

SD PNDMScheduler + Unet example through Turbine

---

core/shark_turbine/aot/builtins/jittable.py
core/shark_turbine/importers/fx_importer.py

I was hoping that we could just depend on it via IREE, but it needed some local patches (sending upstream) for type imports that don't exist in old versions of PyTorch. So for now, just updating the local fork.

Sync fx_importer from torch-mlir.

---

README.md

zsh uses square brackets for pattern matching which means that if you need to pass literal square brackets as an argument to a command, you either need to escape them or quote the arguments.

Fix README.md installation for zsh

---

.github/workflows/test_shark.yml
core/pytorch-cpu-requirements.txt
models/requirements.txt
models/setup.py

Pin transformers to version 4.37.1 and mpmath to 1.3 to fix the testing failures with the new version until we get it fixed.
Please see #476 for details on reason for testing failure with updated transformers.

pin transformers for llama testing and mpmath for shark testing

---

core/shark_turbine/kernel/_support/tracing.py
core/shark_turbine/kernel/compiler/builder.py
core/shark_turbine/kernel/compiler/vector_codegen.py
core/shark_turbine/kernel/lang/prims.py
core/shark_turbine/kernel/ops/core.py
core/tests/kernel/fused_attention_test.py

This patch adds a test for f16 attention. The fused_attention kernel needed dtype conversion so that is also added. As a side effect, implicit vector conversion (for unary ops) is now also supported.

[TK] Add test for fused attention and ops needed

---

core/shark_turbine/kernel/_support/dtype.py
core/shark_turbine/kernel/_support/indexing.py
core/shark_turbine/kernel/_support/regions.py
core/shark_turbine/kernel/_support/shaped_type.py
core/shark_turbine/kernel/_support/tracing.py
core/shark_turbine/kernel/compiler/dispatch_codegen.py
core/shark_turbine/kernel/compiler/kernel_codegen.py
core/shark_turbine/kernel/compiler/vector_codegen.py
core/shark_turbine/kernel/lang/__init__.py
core/shark_turbine/kernel/lang/grid.py
core/shark_turbine/kernel/lang/kernel_buffer.py
core/tests/kernel/arith_test.py
core/tests/kernel/dispatch_codegen_test.py
core/tests/kernel/fused_attention_test.py
core/tests/kernel/indexing_test.py
core/tests/kernel/simple_kernel_test.py
core/tests/kernel/vector_codegen_test.py

This patch moves out KernelBuffer and Grid into lang and creates a ShapedType/ShapedDataType class in _support/shaped_type which can be used elsewhere. This is in preparation for VectorType in TK.
This patch also does some other things:
- Removes the string IndexExpr syntax for KernelBuffer/Grid, which I don't think was very useful.
- Changes the syntax of KernelBufffer to include data type

[TK] Refactor ShapedType out of KernelBuffer and Grid

---

core/iree-requirements.txt
core/shark_turbine/dynamo/backends/cpu.py
core/shark_turbine/dynamo/executor.py
core/shark_turbine/dynamo/tensor.py
core/tests/aot/args_test.py
core/tests/aot/globals_test.py

This release pulls in https://github.com/openxla/iree/pull/16486 which makes
substantial changes to torch imports:
* Always generates async code (with a special `$async` suffixed entrypoint that the default entrypoint delegates to).
* Internal structure of the generated code is different, invalidating some tests.

Bump IREE to 20240226.813 and adapt to API breaks. 

---

core/shark_turbine/aot/compiled_module.py
core/shark_turbine/aot/exporter.py
core/shark_turbine/kernel/_support/tracing.py
core/shark_turbine/kernel/gen/__init__.py
core/shark_turbine/kernel/gen/kernel.py
core/shark_turbine/kernel/gen/thread.py
core/shark_turbine/runtime/op_reg/base.py
core/tests/aot/args_test.py
core/tests/aot/globals_test.py
core/tests/aot/jittable_test.py
core/tests/kernel/aot_kernel_test.py

* Adds `tkl.gen.kernel` decorator to generate a registered/callable kernel.
* The kernel can be used in both AOT and eager contexts.
* Adds some support to kernel registration for uniqueing names like these that are not user-facing and can be defined multiple times.
* Changes the CompiledModule phasing to include a custom op expansion phase. Also defaults it to `IMPORT` instead of `FULL` in a couple of low level places where it still had the old default. This is now consistent with expected, canonical usage but still allows importing to IREE's internal IR if desired (i.e. `FULL`).

[TK] Add support to generate tk operations for torch.export

---

models/turbine_models/custom_models/stateless_llama.py

In this implementation, we are splitting up the KV cache to have a global for each layer for each K/V. This will allow for cleaner indexing which will lead to simpler analysis and better perf down the line.
One analysis that we need this for is to check that we have independent reads and writes to KV-cache. We need this to remove redundant copies of KV-cache.  We can also do the same with integrated/big slab but would be much harder since it will require us to analyze dynamic striding and more complex ranges.

[models] Implement KV-cache to have own global for each layer, K, V.

---

llm/turbine_llm/inference/export_paged_llm_v1.py
llm/turbine_llm/layers/core.py
llm/turbine_llm/layers/kv_cache.py
llm/turbine_llm/models/llama.py
llm/turbine_llm/utils/debugging.py

This was a little rough but got through it. Key changes involve removing data-dependent views.
As per previous, I believe we still have a bug in the per step cache management, and we will need to do a detailed per-step comparison of the cache with a reference.

[turbine-llm] Enable dynamic FX tracing of the paged llama model.

---

.github/workflows/test_models.yml
.github/workflows/test_sdxl.yml
models/turbine_models/custom_models/llm_runner.py
models/turbine_models/custom_models/stateless_llama.py
models/turbine_models/model_builder.py
models/turbine_models/tests/stateless_llama_test.py

This commit cleans up stateless llama testing and helps with memory efficiency by creating the model on the Meta device (with empty weights) and the state dict is then loaded inside it (shard by shard in the case of a sharded checkpoint). The sd test for `vae_encode` throws an error. I took a look at the mlir generated and the `encode_inp func` is there and inputs/return looks valid. Looks like it has to do with iree bump (`FuncConversion` pass). It also adds a CI job to run Jinchen's sdxl script nightly (one failure right now, hopefully fixed soon).

Stateless llama testing + SDXL CI Job

---

models/turbine_models/custom_models/sd_inference/clip.py
models/turbine_models/custom_models/sd_inference/schedulers.py
models/turbine_models/custom_models/sd_inference/unet.py
models/turbine_models/custom_models/sd_inference/utils.py
models/turbine_models/custom_models/sd_inference/vae.py
models/turbine_models/custom_models/stateless_llama.py
models/turbine_models/tests/sd_test.py
models/turbine_models/tests/stateless_llama_test.py
models/turbine_models/turbine_tank/turbine_tank.py

This commit makes minor changes to the model testing and base models, so that there is a difference between validated and failing mlir names in the turbinetank.

update tank and add validation distinction for uploaded names

---

core/shark_turbine/aot/__init__.py
core/shark_turbine/aot/builtins/jittable.py
core/shark_turbine/aot/decompositions.py
core/shark_turbine/aot/exporter.py
core/shark_turbine/aot/fx_programs.py
core/shark_turbine/dynamo/decompositions.py
core/shark_turbine/dynamo/passes.py
core/tests/aot/decompositions_test.py
core/tests/runtime/op_reg/kernel_aot_test.py

This was accidentally left out of the PyTorch 2.3 upgrade rework.
Adds APIs to manage decompositions with a context manager so that we don't thread it through every API permutation.
Exposes a bug in PyTorch 2.3 for decompositions with programs that use python registered ops: https://github.com/pytorch/pytorch/issues/122752 (I have included a really gross workaround).

Enable decompositions for aot.export and torch.export helpers.

---

core/shark_turbine/transforms/merger.py
core/shark_turbine/transforms/rewriter.py

To support rewriting custom dispatches into modules we need to support merging hal executables into modules. This occurs when rewriting in `flow.dispatch` operations.

[rewriter] Add support for `hal` executables for merging modules

---

.github/workflows/test_models.yml
models/turbine_models/custom_models/llm_runner.py
models/turbine_models/tests/stateless_llama_test.py

This commit fixes the stateless llama testing. Basically, with the setup + teardown approach of pytest unit testing, all the tests were sharing the same model from hugging face. We were running the streaming llama tests before the other tests. In these tests (run_torch_llm and export_transformer_model with streaming_llm=True), we do `enable_llama_pos_shift_attention(model)`, which changes the model we are using. So, this was giving us inaccurate results by the time it came to our base vmfb_comparison test. I created this issue to track and provide more info on the error we are now seeing with torch 2.3 in `test_ test_vmfb_comparison`: https://github.com/nod-ai/SHARK-Turbine/issues/601. Also, marked it as an expected failure for now. (changed runner because we are using previous machine to …

fix stateless llama testing

---

.github/workflows/test_models.yml

Swtiched Gentoo runner from ephemeral to persistent. Now, the python action is not supported for the arch. Minor changes to support the persistent runner.

change for persistent Gentoo runner

---

core/iree-requirements.txt
core/shark_turbine/aot/__init__.py
core/shark_turbine/aot/compiled_module.py
core/shark_turbine/aot/exporter.py
core/shark_turbine/aot/params.py
core/shark_turbine/aot/support/ir_utils.py
core/shark_turbine/aot/support/procedural/exported_program.py
core/shark_turbine/aot/tensor_traits.py
core/tests/aot/api_test.py
core/tests/aot/compiled_exported_program_test.py
core/tests/aot/globals_test.py
core/tests/aot/params_test.py
llm/turbine_llm/examples/export_paged_llm_v1.py
llm/turbine_llm/layers/data.py
llm/turbine_llm/layers/gguf/base.py

This changes the behavior of `aot.export()` by:
* Auto exporting literal tensors that are not otherwise configured. This uses a heuristic to decide whether to inline them or emit them as uniqued, out of line globals.
* Removes the options to `externalize_params=` on `export`. This is now done explicitly by the user prior to calling `export` (see below). This feature was never fully usable like this so it is not believed to have any live uses (people who were using external params features were constructing their own `CompiledModule` exactly as they wanted).
* Adds explicit typing overloads for the four use cases:
* Export a `torch.nn.Module` (via `torch.export`)
* Export a pre-constructed `CompiledModule` as a single entry-point
* Export a pre-exported `torch.export.ExportedProgram` as a …

Support auto externalization of tensors/params/buffers and normalize export API.

---

build_tools/build_release.py
core/iree/turbine/__init__.py
core/requirements.txt
core/setup.py
core/tests/top_level_package_test.py
docs/releasing.md
version_info.json

Includes some scripting and release documentation updates that have been in my queue for a while.
In this version, we start executing on the change to deploy the `iree-turbine` package and the `iree.turbine` namespace. This is just a copy of the shark-turbine package currently and the top level namespace is just a redirect of the public API. The next release will complete the switchover.
Since this is pushed as an rc, it is a pre-release requiring installation with the `--pre` flag. When torch 2.3.0 drops, we should push a final.

Release pre-release 2.3.0rc20240410.

---

llm/turbine_llm/examples/export_paged_llm_v1.py
llm/turbine_llm/examples/paged_llm_v1.py
llm/turbine_llm/examples/validate_paged_llama_model.py
llm/turbine_llm/layers/__init__.py
llm/turbine_llm/layers/configs/llm_configs.py
llm/turbine_llm/layers/kv_cache.py
llm/turbine_llm/models/llama/llama.py

I still want to do more work on configs and how to construct models, but this at least unifies the implementations for paged and direct.

[llm] Generalize the KV cache to support both direct and paged caches.

---

core/shark_turbine/aot/exporter.py
core/tests/aot/api_test.py

I was hitting an assert trying to pass a subclass of `CompiledModule` through the `aot.export()` API. The code looked correct, but the metaclass code here: https://github.com/nod-ai/SHARK-Turbine/blob/b22dc7f77cab3bc7a7e29ae73398468799edf713/core/shark_turbine/aot/compiled_module.py#L429 could be affecting the check. I looked through https://stackoverflow.com/questions/33347131/determine-if-a-class-in-python-is-a-metaclass for ideas on how to fix.

Fix assert on `aot.export()` with CompiledModule subclasses.

---

README.md
core/README.md
core/iree/turbine/__init__.py
core/setup.py
core/shark_turbine/aot/__init__.py

Miscellaneous changes found from scanning some of the files. More to come, especially with the `shark-turbine` -> `iree-turbine` switch in progress.
---
The `__init__.py` changes add descriptions when using `help()` in Python, e.g.
```python
>>> help(iree.turbine)
Help on package iree.turbine in iree:
NAME
iree.turbine
DESCRIPTION
The turbine package provides development tools for deploying PyTorch 2 machine
learning models to cloud and edge devices.
```
```python
>>> import shark_turbine.aot as aot
>>> help(aot)
Help on package shark_turbine.aot in shark_turbine:
NAME
shark_turbine.aot - Toolkit for ahead-of-time (AOT) compilation and export of PyTorch programs.
PACKAGE CONTENTS
builtins (package)
compiled_module
decompositions
exporter
fx_programs
params
passes (package)
tensor_traits …
```

Documentation touchups to README and package files.

---

build_tools/build_release.py
core/requirements.txt

The `openxla.github.io` link depends on a specific GitHub organization, and the IREE repo will be moving soon (multiple times). The `iree.dev` release links URL is recommended here: https://iree.dev/reference/bindings/python/#prebuilt-packages

Update IREE pip-release-links URL.

---

.github/workflows/test_models.yml
models/turbine_models/model_runner.py

`vmfbRunner` now takes an optional `extra_plugin` argument to load an executable plugin while the driver is getting created.
This option might be used, for example, when loading a vmfb that has an external dependency on a native shared library.
The implementation of this new feature takes advantage of the pre-existing `iree.runtime.flags` feature and a new IREE python API function.  Normally, drivers are managed in a cache.  However, setting a flag to specify the plugin has no effect on existing drivers.  The API now has a function for creating a driver independent of the cache, to guarantee that any flags are sure to take effect.
This PR also includes a fix for the problem of the CI using old cached wheels for iree, as recommended by @monorimet.

Add ability to include a plugin when creating driver

---

models/turbine_models/tests/sd_test.py

Segfaults otherwise on certain runners.

(SD) Cleanup after each test.

---

models/turbine_models/custom_models/pipeline_base.py
models/turbine_models/custom_models/sd_inference/sd_cmd_opts.py
models/turbine_models/custom_models/sd_inference/sd_pipeline.py

usage:
`--benchmark=all`
`--benchmark=unet`
`--benchmark=clip,vae`
`--verbose`

(SD) Add benchmark option and add a printer.

---

models/turbine_models/custom_models/sd_inference/utils.py
models/turbine_models/custom_models/sd_inference/vae.py

Sync flags to sdxl-scripts repo

Sync flags to sdxl-scripts repo

---

models/turbine_models/custom_models/resnet_18.py
models/turbine_models/custom_models/stateless_llama.py

This commit updates to use dynamic_shapes for dynamic dimensions as the usage of constraints is deprecated in torch 2.4. (The SHARK test checks out the main branch of this repo and will pass once this is merged)

Update constraints to torch 2.4 dynamic_shapes API

---

models/turbine_models/custom_models/llm_runner.py

1. System prompt: remove \<s>; token [1] is generated by default.
2. End of System prompt:
```
Before:         -> After
\n\n               \n\n"""
=> Origin code implies three \n.
"""
```
4. Fix append_user_prompt & append_bot_prompt to match behavior of
`tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)`
Correct Format for LLama2:
```
<s>[INST] <<SYS>>
{{ system_prompt }}
<</SYS>>
{{ user_msg_1 }} [/INST] {{ model_answer_1 }} </s><s>[INST] {{ user_msg_2 }} [/INST]
```

Fix prompt format mismatch with huggingface

---

models/requirements.txt

The package name was changed from `shark-turbine` to `iree-turbine` with iree-org/iree-turbine@40016ad.

Fix installing iree-turbine
