- sync_deps.py
Processing dep iree
iree: 7e353e079 2023-07-19 09:44:45 -0700 : In ireeCompilerRegisterDialects, register all global plugin dialects. (#14432)
Processing dep torch-mlir
torch-mlir: 718f53ff 2023-07-17 09:52:04 -0700 : Fix handling of `!torch.number` in abstract interpretation library (#2309)
> Bump to head versions.

- build_tools/ci/build_linux_packages.sh
> Build the compiler in release mode.

- python/shark_turbine/dynamo/tensor.py
> Refactor get_itemsize() into a dictionary lookup

- python/shark_turbine/dynamo/importer.py
Implemented symbol table to prevent redefinition of symbol named during backward(). `loss.backward()` in an example test case will call `import_stateless_graph()` again, and thus requires func symbol name inside module not to be redefined.
Now with the symbol table implemented, we no longer check against a set() that stores previously used func names as we used to do in PR #25.
After `FuncOp` is initially created in the FX Importer, `self.symbol_table.insert(func)` insertion renames this symbol in the symbol table.
> Implemented symbol table to prevent redefinition of func symbol name

- python/shark_turbine/dynamo/importer.py
- python/test/dynamo/importer_dynamic_test.py
Implements support for symbolic shapes by parsing SymScalars from the Dynamo Fx Graph in our Importer
(as always, inspiration and credit is owed to the original torch-mlir importer)
> Implement support for symbolic shapes

- .github/workflows/test.yml
Added Python CI 
(first time implementing it, so it needs to be tested through this PR)
> Added Python CI

- .github/workflows/test.yml
- tests/dynamo/importer_basic_test.py
> Continuing improving CI

- tests/dynamo/importer_basic_test.py
- tests/dynamo/llama_test.py
- tests/dynamo/mninst_test.py
A test file for MNIST training / (TODO) inference. 
We can land this to the main, and work debugging from there.
Currently, getting `error: failed to legalize operation 'arith.sitofp' that was explicitly marked illegal`.
> Test case for MNIST 

- python/shark_turbine/aot/builtins/jittable.py
- python/shark_turbine/aot/support/procedural/base.py
- python/shark_turbine/aot/support/procedural/globals.py
- python/shark_turbine/aot/support/procedural/iree_emitter.py
- python/shark_turbine/aot/support/procedural/primitives.py
- tests/aot/globals_test.py
The global and immediate Ir{Scalar|Tensor} hierarchy was unfortunately divergent. This unifies it and makes the test pass.
> Make tensor updates to a global work.

- python/shark_turbine/aot/builtins/jittable.py
- python/shark_turbine/aot/support/procedural/primitives.py
- tests/aot/args_test.py
- tests/aot/jittable_test.py
Please review commit by commit. They will be landed to main individually.
> Structured args/returns and dynamic shapes for dynamo.

- python/shark_turbine/aot/builtins/jittable.py
- python/shark_turbine/aot/passes/__init__.py
- python/shark_turbine/aot/passes/functorch.py
- tests/aot/functionalize_test.py
Lots of corners here that I tried to document, but seems to work.
> Add functorch functionalize pass as a pre-processor to AOT pipeline.

- tests/aot/globals_test.py
doing a flow tensor update on a global but returning none seems to cause the compiler to optimize out the update
> add a test that updates without a return value

- requirements.txt
(picks up external parameter fixes)
> Bump IREE to 20231110.704.

- examples/llama2_inference/README.md
This should make it easier to get started with llama2_inference. No more poking around with dependencies.
> Create README.md and quick start script for llama2_inference

- requirements.txt
- turbine-models-requirements.txt
- Updates iree version in requirements.txt for hal fence fix.
- Adds requirements.txt for additional deps on stateless_llama.py and gen_external_params.py
> Requirements update

- python/shark_turbine/aot/support/ir_utils.py
- python/turbine_models/custom_models/stateless_llama.py
- python/turbine_models/gen_external_params/gen_external_params.py
- Adds precision flag for stateless_llama and gen_external_params
- Saves f16 or f32 weights to external params from gen_external_params
- Saves IR/vmfb for f16 or f32 model from stateless_llama
> Adds precision flag for f32 or f16 precision

- python/shark_turbine/importers/ir.py
- python/shark_turbine/importers/onnx_importer.py
Added per docs I am working on for the torch lowerings: https://github.com/llvm/torch-mlir/pull/2585
> Add ONNX metadata and versions as MLIR attributes.

- python/shark_turbine/kernel/_support/context.py
- python/shark_turbine/kernel/_support/indexing.py
- python/shark_turbine/kernel/_support/tracing.py
- python/shark_turbine/kernel/compiler/ir.py
- python/shark_turbine/kernel/compiler/vector_codegen.py
- python/shark_turbine/kernel/lang/__init__.py
- python/shark_turbine/kernel/lang/prims.py
- python/shark_turbine/kernel/lang/types.py
- python/shark_turbine/kernel/ops/__init__.py
- python/shark_turbine/kernel/ops/base.py
- python/shark_turbine/kernel/ops/core.py
- tests/kernel/types_test.py
- tests/kernel/vector_codegen_test.py
* Python value/type propagation
* Loads/stores between KernelBuffer and vectors
* Extended Python integer types
* Python scalar operations
> [tk] Implement basic vector and scalar code generation

- python/shark_turbine/kernel/compiler/builder.py
- python/shark_turbine/kernel/compiler/dispatch_codegen.py
- python/shark_turbine/kernel/compiler/ir.py
- python/shark_turbine/kernel/compiler/kernel_codegen.py
- python/shark_turbine/kernel/compiler/vector_codegen.py
- tests/kernel/dispatch_codegen_test.py
- tests/kernel/vector_codegen_test.py
This is still very much a work in progress as it skates over a number of tricky issues to address when doing code emission to an actual dispatch/stream executable. Specifically, this is as far as I can go without building out symbolic expression support, since that is what is needed for the workgroup calculations. This is also skating by on dynamic shapes for the moment, although most of the plumbing is in place to do it right.
> [tk] Implement stream kernel code generation and hook to vector

- python/shark_turbine/dynamo/passes.py
- python/shark_turbine/importers/fx_importer.py
- python/turbine_models/custom_models/sd_inference/unet.py
- python/turbine_models/custom_models/sd_inference/vae.py
- python/turbine_models/custom_models/sd_inference/vae_runner.py
- python/turbine_models/setup.py
- tests/dynamo/importer_basic_test.py
- turbine-models-requirements.txt
@aviator19941 do we have this pinned to such an old version intentionally?
> (turbine-models) update diffusers version requirement

- requirements.txt
Some important patches came with this release, and if stable, will plan to push to PyPi.
> Bump iree to 20240129.785.

- core/shark_turbine/dynamo/utils.py
This was causing an exception at startup and blocking any other work on Torch 2.2.0 compat.
> Conditionally add the sdpa decomposition only for Torch < 2.2.0.

- .github/workflows/test_models.yml
- models/turbine_models/custom_models/llama_benchmark/stateless_llama_benchmark.py
- models/turbine_models/tests/conftest.py
- models/turbine_models/tests/sdxl_test.py
- models/turbine_models/utils/benchmark.py
- models/turbine_models/utils/sdxl_benchmark.py
For running sdxl pytest on appropriate CI with different backends
TODO: Run iree-tracy-capture subprocess when getting tracy profile; Build IREE from source with `-DIREE_BUILD_TRACY=ON`  for CI job
> Pass command line args for sdxl pytest

- core/shark_turbine/aot/builtins/jittable.py
- core/shark_turbine/importers/fx_importer.py
- models/requirements.txt
- models/turbine_models/custom_models/sd_inference/schedulers_runner.py
- models/turbine_models/custom_models/sd_inference/sdxl_schedulers.py
- models/turbine_models/custom_models/sd_inference/sdxl_split_schedulers.py
- models/turbine_models/custom_models/sd_inference/utils.py
- models/turbine_models/custom_models/sdxl_inference/sdxl_schedulers.py
so we don't have to carry all these branches
> Support for SDXL schedulers + example

- .github/workflows/test_models.yml
- models/turbine_models/tests/conftest.py
- models/turbine_models/tests/sd_test.py
- models/turbine_models/tests/sdxl_test.py
stateless_llama test breaks;
sd_test has same issues on unet and vae: https://gist.github.com/jinchen62/11684b457c438b54a363077d0fafbe27
> fix sd/sdxl CI

- core/iree-requirements.txt
adds support for pytorch 2.3 in fx_importer
> bump iree to 20240311.828

- .github/workflows/test_models.yml
mi210 is not working as expected at the moment for some reason
> Change back to mi250

- models/turbine_models/custom_models/sdxl_inference/unet.py
The reason for updating the revision hash is this PR by Stella in sharktank: https://github.com/nod-ai/sharktank/pull/93. Because we are using sharktank TOM, we need to update here too so that it gives sharktank the expected quant_params.json.
> Minor fixes for SDXL/unet

- models/turbine_models/custom_models/sd_inference/sd_pipeline.py
Fixes a filename constructor for expected vmfb filename so that it matches what is exported.
> (SD) Fix precompiled vmfb loading for schedulers.

- models/turbine_models/custom_models/sd_inference/sd_pipeline.py
Otherwise goes down the wrong pipeline
> Fix typo for hf model name

- models/turbine_models/custom_models/sd_inference/sd_pipeline.py
- models/turbine_models/custom_models/sd_inference/utils.py
- models/turbine_models/custom_models/sdxl_inference/unet.py
Currently using a link, but Nithin will be pushing the fix to use a file name asap
> Integration of tk kernels into pipeline

- .github/workflows/test_models.yml
- .github/workflows/test_sdxl.yml
- .github/workflows/test_shark.yml
Pins as suggested by OpenSSF Scorecard, see
https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies.
> Pin `action/checkout` action

- models/turbine_models/custom_models/sdxl_inference/sdxl_prompt_encoder.py
Fix turbine import.
Revert change to prompt encoder filename.
Update sdxl_prompt_encoder.py
> Force clip sdpa decomposition
